import { ArrowUpRight, Check, MousePointer2, PenLine, RectangleHorizontal, Trash2, Type } from 'lucide-react';
import { canvasSize, cropPixels, fullCrop, outputSize, placement, ratios, uid } from '../types';
import type { Annotation, Edits, Source, Tool } from '../types';
import { filters } from '../effects';
import type { DrawMode } from './Preview';
type Props={hidden:boolean;onClose:()=>void;source:Source;edits:Edits;tool:Tool;selectedAnnotation:string|null;drawMode:DrawMode;drawColor:string;thumbnail?:string;onUpdate:(patch:Partial<Edits>,record?:boolean)=>void;onCheckpoint:()=>void;onAnnotation:(id:string|null)=>void;onDrawMode:(mode:DrawMode)=>void;onDrawColor:(color:string)=>void};
const names:Record<Tool,string>={canvas:'Frame',crop:'Crop',filters:'Filters',annotate:'Annotate',speed:'Speed'};
const filterCSS:Record<string,string>={Original:'none',Mono:'grayscale(1)',Warm:'sepia(.3) saturate(1.2)',Cool:'saturate(.8) hue-rotate(12deg)',Soft:'contrast(.85) brightness(1.1)',Vivid:'saturate(1.4) contrast(1.1)'};
export default function ToolPanel(p:Props){
  const {source,edits,tool,onUpdate}=p;const custom={width:edits.canvas.customWidth||16,height:edits.canvas.customHeight||9};
  const colors=['#ffffff','#1a1d18','#e8e76a','#f599a7','#9bc772','#8eb8fa'];
  const annotation=edits.annotations.find(a=>a.id===p.selectedAnnotation);
  const pixels=cropPixels(source,edits.crop),canvas=canvasSize(source,edits),output=outputSize(source,edits);
  const placed=placement(source,edits,canvas);
  const backgroundVisible=placed.width<canvas.width-2||placed.height<canvas.height-2;
  const editAnnotation=(patch:Partial<Annotation>,record=true)=>{if(annotation)onUpdate({annotations:edits.annotations.map(a=>a.id===annotation.id?{...a,...patch}:a)},record);};
  const addText=()=>{const a:Annotation={id:uid(),type:'text',text:'Your text',x:.5,y:.78,width:0,height:0,color:p.drawColor,size:.065};onUpdate({annotations:[...edits.annotations,a]});p.onAnnotation(a.id);p.onDrawMode('select');};
  const chooseCrop=(aspect:string)=>{
    if(aspect==='Original'){onUpdate({cropAspect:aspect,crop:{...fullCrop}});return;}
    if(aspect==='Free'){onUpdate({cropAspect:aspect});return;}
    const r=ratios[aspect]/(source.width/source.height),width=Math.min(1,r),height=Math.min(1,1/r);
    onUpdate({cropAspect:aspect,crop:{x:(1-width)/2,y:(1-height)/2,width,height}});
  };
  const slider=(label:string,value:number,min:number,max:number,change:(v:number)=>void,suffix='')=><label className="property-slider"><span>{label}<output>{value}{suffix}</output></span><input type="range" aria-label={label} min={min} max={max} value={value} onPointerDown={p.onCheckpoint} onKeyDown={e=>{if(e.key.startsWith('Arrow'))p.onCheckpoint();}} onChange={e=>change(Number(e.target.value))}/></label>;
  return <aside id="tool-settings" hidden={p.hidden} className="inspector" aria-label={`${names[tool]} settings`}><div className="inspector-title"><h2>{names[tool]}</h2><span>{tool==='canvas'?'01':tool==='crop'?'02':tool==='filters'?'03':tool==='annotate'?'04':'05'}</span><button className="close-settings text-button" onClick={p.onClose} aria-label={`Close ${names[tool]} settings`}><Check size={15}/>Done</button></div>
    {tool==='canvas'&&<><p className="panel-intro">A frame for wherever it’s going.</p><div className="canvas-presets">{[{name:'Original',ratio:null,label:'Original'},{name:'16:9',ratio:16/9,label:'Landscape'},{name:'9:16',ratio:9/16,label:'Portrait'},{name:'1:1',ratio:1,label:'Square'},{name:'4:5',ratio:4/5,label:'Social'},{name:'4:3',ratio:4/3,label:'Classic'},{name:'21:9',ratio:21/9,label:'Wide'},{name:'Custom',ratio:Math.max(.2,Math.min(5,custom.width/custom.height)),label:'Custom'}].map(item=><button key={item.name} aria-pressed={edits.canvas.aspect===item.name} onClick={()=>onUpdate({canvas:{...edits.canvas,aspect:item.name,ratio:item.ratio},resolution:'original'})}><span className="ratio-icon" style={{aspectRatio:item.ratio||source.width/source.height,width:!item.ratio||item.ratio>=1?'25px':'16px'}}/><span>{item.label}</span><small>{item.name==='Original'?'auto':item.name==='Custom'?'W : H':item.name}</small></button>)}</div>
      {edits.canvas.aspect==='Custom'&&<div className="custom-ratio">{(['width','height'] as const).map(key=><label key={key}>{key==='width'?'Width':'Height'}<input type="number" aria-label={`Canvas ratio ${key}`} min="1" max="8192" value={custom[key]} onChange={e=>{const next={...custom,[key]:Math.max(1,Math.min(8192,Number(e.target.value)||1))};const ratio=next.width/next.height;onUpdate({canvas:{...edits.canvas,customWidth:next.width,customHeight:next.height,...(ratio>=.2&&ratio<=5?{ratio}:{})},resolution:'original'});}}/></label>)}<span>Ratio from 1:5 to 5:1</span></div>}
      <div className="property-section"><span className="property-label">Video in frame</span><div className="segmented-control">{(['fit','fill'] as const).map(fit=><button key={fit} aria-pressed={edits.canvas.fit===fit} onClick={()=>onUpdate({canvas:{...edits.canvas,fit}})}>{fit==='fit'?'Fit whole video':'Fill frame'}</button>)}</div></div>
      {edits.canvas.fit==='fit'&&<div className="property-section">{slider('Inset',edits.canvas.inset,0,20,inset=>onUpdate({canvas:{...edits.canvas,inset}},false),'%')}<span className="property-label">Background</span><div className="color-options">{['#171717','#ffffff','#e5e5e5','#c4d4df'].map(color=><button key={color} aria-label={`Background ${color}`} aria-pressed={edits.canvas.background===color} style={{background:color}} onClick={()=>onUpdate({canvas:{...edits.canvas,background:color}})}/>)}<label className="custom-color" title="Custom background color"><input type="color" aria-label="Custom background color" value={edits.canvas.background} onChange={e=>onUpdate({canvas:{...edits.canvas,background:e.target.value}})}/><span>+</span></label></div>{!backgroundVisible&&<p className="background-note">Add an inset or change the frame ratio to reveal the background.</p>}</div>}
      <label className="property-section field-label">Resolution<select aria-label="Edit resolution" value={edits.resolution} onChange={e=>onUpdate({resolution:e.target.value})}><option value="original">Original</option>{[2160,1440,1080,720,480,360].filter(n=>n<Math.min(canvas.width,canvas.height)).map(n=><option key={n} value={n}>{n}p</option>)}</select></label><span className="dimension-note">{output.width} × {output.height} px</span></>}
    {tool==='crop'&&<><p className="panel-intro">Bring the details into focus.</p><span className="property-label">Crop ratio</span><div className="crop-ratios">{['Free','Original','1:1','16:9','9:16','4:3'].map(a=><button key={a} aria-pressed={edits.cropAspect===a} onClick={()=>chooseCrop(a)}>{a}</button>)}</div><div className="property-section crop-dimensions"><span>Selection</span><strong>{pixels.width} × {pixels.height}</strong></div><p className="panel-note">Drag the corners to resize. Drag inside to reposition.</p><button className="text-button" onClick={()=>onUpdate({crop:{...fullCrop},cropAspect:'Free'})}>Reset crop</button></>}
    {tool==='filters'&&<><p className="panel-intro">A little change of mood.</p><div className="filter-options">{filters.map(filter=><button key={filter} aria-pressed={edits.filter===filter} onClick={()=>onUpdate({filter})}><span>{p.thumbnail?<img src={p.thumbnail} alt="" style={{filter:filterCSS[filter]}}/>:<i className="filter-placeholder" style={{filter:filterCSS[filter]}}/>}{edits.filter===filter&&<i className="filter-check"><Check size={12}/></i>}</span>{filter}</button>)}</div><div className="property-section">{slider('Intensity',edits.intensity,0,100,intensity=>onUpdate({intensity},false),'%')}{slider('Brightness',edits.brightness,-30,30,brightness=>onUpdate({brightness},false))}{slider('Contrast',edits.contrast,-30,30,contrast=>onUpdate({contrast},false))}</div><button className="text-button" onClick={()=>onUpdate({filter:'Original',intensity:100,brightness:0,contrast:0})}>Reset filters</button></>}
    {tool==='annotate'&&<><p className="panel-intro">Point out what matters.</p><div className="annotation-tools"><button aria-label="Select annotations" aria-pressed={p.drawMode==='select'} onClick={()=>p.onDrawMode('select')}><MousePointer2 size={17}/></button><button aria-label="Add text" onClick={addText}><Type size={17}/></button>{([{mode:'arrow',icon:ArrowUpRight,label:'Draw arrow'},{mode:'rectangle',icon:RectangleHorizontal,label:'Draw rectangle'},{mode:'pen',icon:PenLine,label:'Draw freehand'}] as const).map(({mode,icon:Icon,label})=><button key={mode} aria-label={label} aria-pressed={p.drawMode===mode} onClick={()=>{p.onDrawMode(mode);p.onAnnotation(null);}}><Icon size={17}/></button>)}</div><div className="property-section"><span className="property-label">Color</span><div className="color-options">{colors.map(color=><button key={color} aria-label={`Annotation color ${color}`} aria-pressed={(annotation?.color||p.drawColor)===color} style={{background:color}} onClick={()=>{p.onDrawColor(color);editAnnotation({color});}}/>)}</div></div>
      {annotation?.type==='text'&&<label className="field-label property-section">Text<textarea aria-label="Annotation text" value={annotation.text} rows={3} maxLength={200} onFocus={p.onCheckpoint} onChange={e=>editAnnotation({text:e.target.value},false)}/></label>}
      {annotation&&<div className="property-section">{slider(annotation.type==='text'?'Text size':'Stroke width',Math.round(annotation.size*1000),annotation.type==='text'?20:2,annotation.type==='text'?160:20,v=>editAnnotation({size:v/1000},false))}</div>}
      {edits.annotations.length>0&&<div className="property-section"><span className="property-label">On your video <small>{edits.annotations.length}</small></span><div className="annotation-list">{edits.annotations.map((a,i)=><button key={a.id} className={p.selectedAnnotation===a.id?'active':''} onClick={()=>{p.onAnnotation(a.id);p.onDrawMode('select');}}><span style={{background:a.color}}/><span>{a.type==='text'?a.text||'Empty text':`${a.type==='pen'?'Drawing':a.type[0].toUpperCase()+a.type.slice(1)} ${i+1}`}</span></button>)}</div></div>}
      {annotation&&<button className="text-button danger" onClick={()=>{onUpdate({annotations:edits.annotations.filter(a=>a.id!==annotation.id)});p.onAnnotation(null);}}><Trash2 size={13}/>Delete annotation</button>}<p className="panel-note">Annotations stay visible throughout the video. Select one to move or edit it.</p></>}
    {tool==='speed'&&<><p className="panel-intro">Set your own pace.</p><div className="speed-presets">{[.25,.5,.75,1,1.25,1.5,2,3,4].map(speed=><button key={speed} aria-pressed={edits.speed===speed} onClick={()=>onUpdate({speed})}>{speed}×</button>)}</div><p className="panel-note">Applies to every clip. Audio follows along and keeps its pitch.</p><label className="mute-setting"><span>Keep audio</span><input type="checkbox" role="switch" aria-label="Keep audio" checked={!edits.muted} onChange={e=>onUpdate({muted:!e.target.checked})}/></label></>}
  </aside>;
}
