import { action, select } from './ui.mjs';
import { chromium } from 'playwright-core';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import path from 'node:path';
const sample=process.env.VIDEO_SAMPLE,sample4k=process.env.VIDEO_4K_SAMPLE;
if(!sample||!sample4k)throw new Error('Set VIDEO_SAMPLE (8s, 1280×720, with audio) and VIDEO_4K_SAMPLE (0.5s, 3840×2160, silent).');
const out=process.env.VERIFY_OUTPUT||'/tmp/snip-verification';mkdirSync(out,{recursive:true});
const browser=await chromium.connectOverCDP(process.env.CDP_URL||'http://127.0.0.1:19376');
const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});
const page=await context.newPage();page.setDefaultTimeout(15000);
const errors=[],requests=[],report=[];const app=process.env.APP_URL||'http://127.0.0.1:5186';
page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().startsWith('http'))requests.push({method:r.method(),url:r.url()});});
const log=(check,data={})=>{report.push({check,...data});console.log('PASS',check,JSON.stringify(data));};
const button=name=>action(page,name);
const probe=file=>JSON.parse(execFileSync(process.env.FFPROBE_PATH||'ffprobe',['-v','error','-show_streams','-show_format','-of','json',file],{encoding:'utf8'}));
const seek=async time=>{await page.getByRole('slider',{name:'Seek video',exact:true}).fill(String(time));await page.waitForFunction(t=>Math.abs(document.querySelector('.seek input[type=range]').value-t)<.01,time);};
const count=()=>page.locator('.timeline-clip').count();
async function open(file){const name=`test-${Date.now()}-${path.basename(file)}`;await page.locator('#video-file').setInputFiles({name,mimeType:file.endsWith('.webm')?'video/webm':'video/mp4',buffer:readFileSync(file)});await page.locator('.file-info>span').filter({hasText:name}).waitFor();await page.waitForFunction(()=>document.querySelector('video')?.readyState>=2);}
async function exportFile(name,format='mp4',resolution='360'){
  await button('Export video').click();await select(page,'Export format',format);await select(page,'Export resolution',resolution);
  const waiting=page.waitForEvent('download',{timeout:120000});await button('Export & download').click();const download=await waiting;const file=path.join(out,name);await download.saveAs(file);assert.equal(await download.failure(),null);
  await page.getByRole('heading',{name:'Your video is ready'}).waitFor();await button('Back to editing').click();const info=probe(file);return{file,info,video:info.streams.find(s=>s.codec_type==='video'),audio:info.streams.find(s=>s.codec_type==='audio')};
}
async function draw(name,start,end,points=1){await button(name).click();const box=await page.locator('.composition').boundingBox();await page.mouse.move(box.x+start[0]*box.width,box.y+start[1]*box.height);await page.mouse.down();await page.mouse.move(box.x+end[0]*box.width,box.y+end[1]*box.height,{steps:points});await page.mouse.up();}
try{
  await page.goto(app);await page.waitForFunction(()=>navigator.serviceWorker.controller!==null);await open(sample);
  assert.equal(await page.getByRole('textbox',{name:'From',exact:true}).count(),0);assert.equal(await page.getByRole('textbox',{name:'To',exact:true}).count(),0);
  await page.waitForFunction(()=>document.querySelectorAll('.clip-thumbnails img').length>5);log('Real timeline thumbnails; old From/To inputs removed');
  // Migrate a v1 project using the same stored video. No source re-upload.
  await page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('snip-local-project',1);r.onsuccess=()=>{const db=r.result,t=db.transaction('project','readwrite');t.objectStore('project').put({start:1,end:7,speed:2,crop:{x:0,y:0,width:1,height:1},aspect:'Original',resolution:'original',format:'mp4',quality:'maximum',muted:false},'edits');t.oncomplete=()=>{db.close();resolve(true);};t.onerror=()=>reject(t.error);};}));
  await page.reload();await page.locator('.timeline-clip').waitFor();assert.equal(await page.getByRole('slider',{name:'Clip 1 start',exact:true}).getAttribute('aria-valuenow'),'1');assert.equal(await page.getByRole('slider',{name:'Clip 1 end',exact:true}).getAttribute('aria-valuenow'),'7');assert.equal(await page.getByRole('slider',{name:'Seek video',exact:true}).getAttribute('max'),'3');log('Existing v1 video, trims, and speed migrate safely');
  await open(sample);
  assert.equal(await button('Trim').count(),0);assert.equal(await page.locator('.editor-footer').count(),0);await page.getByRole('status').filter({hasText:'Saved on this device'}).waitFor();
  await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.fonts.check('14px "Inter Variable"')),true);
  assert((await page.locator('body').evaluate(e=>getComputedStyle(e).fontFamily)).includes('Inter Variable'));log('Trim sidebar and footer removed; header save status and locally loaded Inter');
  await button('Go to end').click();assert.equal(await page.getByRole('slider',{name:'Seek video',exact:true}).inputValue(),'8');assert.equal(await page.locator('video').evaluate(v=>v.currentTime),8);
  await select(page,'Playback speed','2');assert.equal(await page.getByRole('slider',{name:'Seek video',exact:true}).inputValue(),'4');assert.equal(await page.locator('video').evaluate(v=>v.currentTime),8);await select(page,'Playback speed','1');await button('Back to start').click();assert.equal(await page.getByRole('slider',{name:'Seek video',exact:true}).inputValue(),'0');
  await select(page,'Playback speed','1.5');assert.equal(await page.locator('video').evaluate(v=>v.playbackRate),1.5);await button('Speed').click();assert.match(await page.getByRole('combobox',{name:'Video speed',exact:true}).innerText(),/1.5×/);await select(page,'Playback speed','1');log('Playback start/end buttons and speed selector stay in sync with Speed settings');
  await seek(2);await page.locator('.timeline-actions button').first().click();await seek(4);await page.locator('.timeline-actions button').first().click();assert.equal(await count(),3);
  await page.locator('.timeline-clip').nth(1).press('Enter');await button('Delete clip').click();assert.equal(await count(),2);assert.equal(await page.getByRole('slider',{name:'Seek video',exact:true}).getAttribute('max'),'6');
  await button('Undo').click();assert.equal(await count(),3);await button('Redo').click();assert.equal(await count(),2);log('Split twice, remove middle section, undo and redo');
  // Drag a clip edge, then undo it as a single operation.
  await page.locator('.timeline-clip').first().press('Enter');const handle=page.getByRole('slider',{name:'Clip 1 end',exact:true});const hb=await handle.boundingBox();await page.mouse.move(hb.x+hb.width/2,hb.y+hb.height/2);await page.mouse.down();await page.mouse.move(hb.x-30,hb.y+hb.height/2,{steps:8});await page.mouse.up();assert(Number(await handle.getAttribute('aria-valuenow'))<1.99);await button('Undo').click();assert.equal(Number(await handle.getAttribute('aria-valuenow')),2);
  await handle.focus();for(let i=0;i<5;i++)await page.keyboard.press('ArrowLeft');await page.locator('.timeline-clip').nth(1).press('Enter');const start=page.getByRole('slider',{name:'Clip 2 start',exact:true});await start.focus();for(let i=0;i<5;i++)await page.keyboard.press('ArrowRight');
  assert(Math.abs(Number(await page.getByRole('slider',{name:'Seek video',exact:true}).getAttribute('max'))-5)<.001);log('Per-clip edge dragging and trims on both sides of an internal cut');
  await seek(1.3);await button('Play').click();await page.waitForFunction(()=>document.querySelector('video').currentTime>4.5);await button('Pause').click();const playback=await page.locator('video').evaluate(v=>v.currentTime);assert(playback<5.5);const head=Number(await page.getByRole('slider',{name:'Seek video',exact:true}).inputValue());assert(head<2.5);log('Preview skips removed footage and playhead follows edited time');
  const cuts=await exportFile('trimmed-sequence.mp4');assert.equal(cuts.video.width,640);assert.equal(cuts.video.height,360);assert.equal(cuts.audio.codec_name,'aac');assert(Math.abs(Number(cuts.info.format.duration)-5)<.08);log('Automatic multi-clip MP4 download',{file:cuts.file,seconds:cuts.info.format.duration,dimensions:[640,360]});
  await button('Frame').click();await page.getByRole('slider',{name:'Inset',exact:true}).fill('8');await button('Background #ffffff').click();
  let geometry=await page.evaluate(()=>{const c=document.querySelector('.composition'),v=document.querySelector('.source-window');return{color:getComputedStyle(c).backgroundColor,frame:c.getBoundingClientRect().toJSON(),video:v.getBoundingClientRect().toJSON()};});assert.equal(geometry.color,'rgb(255, 255, 255)');assert(geometry.video.width<geometry.frame.width);assert(geometry.video.height<geometry.frame.height);
  await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'inset-light.png'),fullPage:true});
  const inset=await exportFile('inset-white.mp4');assert.equal(inset.video.width,640);assert.equal(inset.video.height,360);
  if(process.env.FFMPEG_PATH){const rgb=execFileSync(process.env.FFMPEG_PATH,['-v','error','-i',inset.file,'-frames:v','1','-f','rawvideo','-pix_fmt','rgb24','pipe:1'],{maxBuffer:5e6});const pixel=(x,y)=>Array.from(rgb.subarray((y*640+x)*3,(y*640+x)*3+3));for(const [x,y] of [[8,8],[631,8],[8,351],[631,351]])assert(pixel(x,y).every(v=>v>=248));assert(Math.min(...pixel(150,100))<240);log('Exported frame has the chosen white background on all four sides and preserved video inside');}
  await page.getByLabel('Custom background color',{exact:true}).fill('#4070b0');await page.getByRole('status').filter({hasText:'Saved on this device'}).waitFor();await page.reload();await page.getByRole('slider',{name:'Inset',exact:true}).waitFor();assert.equal(await page.getByRole('slider',{name:'Inset',exact:true}).inputValue(),'8');assert.equal(await page.getByLabel('Custom background color',{exact:true}).inputValue(),'#4070b0');log('Frame inset and custom background persist across refresh');
  await page.getByRole('slider',{name:'Inset',exact:true}).fill('0');await select(page,'Canvas aspect ratio','9:16');geometry=await page.evaluate(()=>{const c=document.querySelector('.composition'),v=document.querySelector('.source-window');return{color:getComputedStyle(c).backgroundColor,frame:c.getBoundingClientRect().toJSON(),video:v.getBoundingClientRect().toJSON()};});assert.equal(geometry.color,'rgb(64, 112, 176)');assert(geometry.video.height<geometry.frame.height);log('Background also appears with a portrait Fit frame');
  await button('Fill frame').click();await button('Filters').click();await button('Mono').click();await button('Speed').click();await select(page,'Video speed','2');
  await button('Annotate').click();await button('Add text').click();await page.getByLabel('Annotation text',{exact:true}).fill('LOOK HERE');
  await page.getByLabel('Annotation color #f599a7',{exact:true}).click(); // Selectable color is also used by new drawings.
  await draw('Draw arrow',[.15,.2],[.7,.35]);await page.getByLabel('Annotation color #e8e76a',{exact:true}).click();await draw('Draw rectangle',[.18,.43],[.78,.61]);await draw('Draw freehand',[.15,.9],[.7,.93],12);
  assert.equal(await page.locator('.annotation-list button').count(),4);log('Text, arrow, rectangle, and freehand annotations');
  await button('Switch to dark mode').click();assert.equal(await page.locator('body').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(23, 23, 23)');assert.equal(await page.locator('.preview-stage').evaluate(e=>getComputedStyle(e).backgroundColor),'rgb(20, 20, 20)');await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'desktop-dark.png'),fullPage:true});
  await context.setOffline(true);await page.reload();await page.locator('.timeline-clip').first().waitFor();assert.equal(await count(),2);assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');await button('Frame').click();assert.match(await page.getByRole('combobox',{name:'Canvas aspect ratio',exact:true}).innerText(),/Portrait/);await button('Annotate').click();assert.equal(await page.locator('.annotation-list button').count(),4);await page.evaluate(()=>document.fonts.ready);assert.equal(await page.evaluate(()=>document.fonts.check('14px \"Inter Variable\"')),true);log('Offline refresh restores clips, portrait frame, annotations, dark mode, and Inter');
  const portrait=await exportFile('portrait-effects.mp4');assert.equal(portrait.video.width,360);assert.equal(portrait.video.height,640);assert(portrait.audio);assert(Math.abs(Number(portrait.info.format.duration)-2.5)<.1);log('Offline portrait MP4: cuts, 2× speed, filter, all annotations',{file:portrait.file,seconds:portrait.info.format.duration});
  const webm=await exportFile('portrait-effects.webm','webm');assert.equal(webm.video.codec_name,'vp8');assert.equal(webm.audio.codec_name,'opus');assert.equal(webm.video.width,360);assert.equal(webm.video.height,640);assert(Math.abs(Number(webm.info.format.duration)-2.5)<.1);log('Offline WebM with the same edits',{file:webm.file});
  await page.setViewportSize({width:390,height:844});assert(await button('Go to end').isVisible());assert(await page.getByLabel('Playback speed',{exact:true}).isVisible());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'mobile-dark.png'),fullPage:true});await button('Project menu').click();await button('Switch to light mode').click();await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'mobile-light.png'),fullPage:true});log('Light and dark mobile layouts fit 390px');
  await page.setViewportSize({width:1440,height:1000});await open(sample4k);await button('Export video').click();await button('Export & download').click();await button('Cancel export').click();await page.getByRole('heading',{name:'Export video',exact:true}).waitFor();await button('Close export').click();
  const fourK=await exportFile('original-4k.mp4','mp4','original');assert.equal(fourK.video.width,3840);assert.equal(fourK.video.height,2160);assert.equal(fourK.audio,undefined);log('Cancel/retry and silent original 4K export');await open(fourK.file);await button('Play').click();await page.waitForFunction(()=>document.querySelector('video').currentTime>0);log('Downloaded export reopens and plays');
  assert.equal(await page.evaluate(()=>document.cookie),'');assert(requests.every(r=>r.method==='GET'&&new URL(r.url).origin===new URL(app).origin));assert.deepEqual(errors,[]);log('No cookies, uploads, external requests, or browser errors');
  writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));
}catch(error){console.error('PAGE',page.url(),await page.locator('body').innerText());await page.waitForTimeout(200);await page.screenshot({path:path.join(out,'failure.png'),fullPage:true});throw error;}
finally{await context.setOffline(false);await context.close();await browser.close();}
